import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Image from 'next/image'
import logo from '../public/images/LogoAppIcon.png'
import { RxHamburgerMenu } from 'react-icons/Rx'

const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): React.ReactElement {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='animationHeader flex bg-red w-full h-24 justify-between items-center px-8'>
          <RxHamburgerMenu size={50} color='blue' />
          <Image src={logo} alt='logo of application' height={100} />
        </header>
        {children}
      </body>
    </html>
  )
}
